services:
  - type: web
    name: nextalk-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_ALLOWED_HOSTS
        value: nextalk-488b.onrender.com,nex-talk-gray.vercel.app,localhost,127.0.0.1
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11.13

  - type: redis
    name: nextalk-redis
    ipAllowList: []
