version: "3.8"
services:
  web:
    build: ./backend
    command: bash -c "python manage.py migrate && uvicorn backend.wsgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
